### ISSUE TITLE
Spring's QVZ lossy compressor for PacBio HiFi quality streams?

### ISSUE THREAD

**Issue by JeromeNi** [shubhamchandak94/Spring#27] opened 2022-12-05 18:51 UTC
Hi, I'm looking to see if I could use the QVZ lossy compressor in SPRING for PacBio HiFi reads. I'm currently testing on the following FASTQ file (https://github.com/PacificBiosciences/DevNet/wiki/Sequel-II-System-Data-Release:-Universal-Human-Reference-(UHR)-Iso-Seq), but gdb shows that it gave me a Segfault at spring::qvz::pmf_increment (index=93, pmf=0x55555c3a34c0). 

Does it seem to be a problem with the entries for the quality scores in HiFi reads? I'm not exactly sure what to modify in the code, but I found one #define ALPHABET_SIZE 72 in qvz.h and one #define ALPHABET_INDEX_SIZE_HINT 72 in pmf.h. I tried setting them to 125 as HiFi reads have quality score range [33, 126]. While the segfault goes away, compressing one single file (as linked above) with rate set to 1.0 for QVZ seems to take forever (it was stuck in "Preprocessing"; I halted after like 20 minutes) on an i7-12700H laptop with 20G free RAM (with default -t 8). Am I missing something with the above modification?

Thanks very much for your help!

**Comment by shubhamchandak94** [comment] 2022-12-06 04:50
Hi Jerome,
Thanks for your message and for looking into this issue. I think QVZ doesn't make much sense for long reads since it uses the position in read as context which is only useful for short reads. I mostly copied the QVZ code from the original repository and made only minor changes. Since QVZ was designed for and tested on short read datasets, I think it's best to use it only for those datasets. For long reads, I would suggest looking at https://github.com/guilledufort/RENANO or https://github.com/refresh-bio/CoLoRd (both support reference-based and reference-free modes). These have specialized quality models for long read datasets (first one is more focused on nanopore though). 
If you really need to run QVZ on pacbio, we might be able to look into it, but I am not sure there is much benefit of using that.
Regards,
Shubham

**Comment by shubhamchandak94** [comment] 2022-12-15 01:28
Closing issue, please reopen in case of further comments.

**Closed by shubhamchandak94** 2022-12-15 01:28 UTC
